Repository code4romania/onghub, pull requests merged in 2023-11, with the labels that each got.

#401 Feat[C4R-354] - Show full label name when user hovers over table column name
  frontend/src/assets/locales/en/translation.json
  frontend/src/assets/locales/ro/translation.json
  frontend/src/components/data-table-name-header/DataTableNameHeader.tsx
  frontend/src/index.css
  frontend/src/pages/application/components/headers/application-ngo-list.headers.tsx
  frontend/src/pages/apps-store/components/ApplicationList.headers.tsx
  frontend/src/pages/apps-store/components/ApplicationRequests.headers.tsx
  frontend/src/pages/civic-center-service/feedback/table-headers/FeedbackListTable.headers.tsx
  frontend/src/pages/organization/components/OrganizationApplications/table-headers/OrganizationApplicationAccessRequestTable.headers.tsx
  frontend/src/pages/organization/components/OrganizationApplications/table-headers/OrganizationApplicationsTable.headers.tsx
  frontend/src/pages/organization/components/OrganizationData/table-headers/InvestorTable.headers.tsx
  frontend/src/pages/organization/components/OrganizationData/table-headers/PartnerTable.headers.tsx
  frontend/src/pages/organization/components/OrganizationData/table-headers/ReportsTable.headers.tsx
  frontend/src/pages/organization/components/OrganizationFinancial/OrganizationFinancialTableHeaders.tsx
  frontend/src/pages/organization/components/OrganizationFinancial/components/ReportTableRow.tsx
  frontend/src/pages/organization/components/OrganizationLegal/table-headers/DirectorsTable.headers.tsx
  frontend/src/pages/organization/components/OrganizationLegal/table-headers/OthersTable.headers.tsx
  frontend/src/pages/organization/table-headers/OrganizationsTable.headers.tsx
  frontend/src/pages/requests/components/RequestList.headers.tsx
  frontend/src/pages/users/components/UserInvites/table-headers/UserInvitesTable.headers.tsx
  frontend/src/pages/users/components/UserList/table-headers/UserListTable.headers.tsx
Labels: enhancement :rocket:

#400 Feat[C4R-333] - User can click to on 'download list' even if there's no list to download
  frontend/src/components/popover-menu/PopoverMenu.tsx
Labels: bug :bug:

#403 fix: [C4R-372] change limit to 7k + remove a console log
  backend/src/common/config/email-config.service.ts
  backend/src/modules/application/dto/create-application.dto.ts
  frontend/src/assets/locales/en/translation.json
  frontend/src/assets/locales/ro/translation.json
  frontend/src/pages/apps-store/components/AddApplicationConfig.ts
Labels: bug :bug:

#404 fix: [C4R-352] add ANAF report regenerate on demand for requests
  backend/src/migrations/1699889886586-SynchedAnaf.ts
  backend/src/modules/organization/constants/errors.constants.ts
  backend/src/modules/organization/controllers/organization.controller.ts
  backend/src/modules/organization/entities/organization-financial.entity.ts
  backend/src/modules/organization/services/organization-financial.service.ts
  backend/src/shared/services/anaf.service.ts
  frontend/src/assets/locales/en/translation.json
  frontend/src/pages/organization/components/OrganizationFinancial/OrganizationFinancial.tsx
  frontend/src/pages/organization/interfaces/OrganizationFinancial.interface.ts
  frontend/src/services/organization/Organization.queries.ts
  frontend/src/services/organization/Organization.service.ts
Labels: bug :bug:

#409 bugfix: [359] Missing user's apps columns and various fixes
  backend/src/migrations/1700316222351-UserApplicationsView.ts
  backend/src/modules/user/admin-user.controller.ts
  backend/src/modules/user/constants/user-filters.config.ts
  backend/src/modules/user/entities/user-applications-view.entity.ts
  backend/src/modules/user/profile.controller.ts
  backend/src/modules/user/repositories/user-applications-view.repository.ts
  backend/src/modules/user/services/user.service.ts
  backend/src/modules/user/user.module.ts
  frontend/src/components/data-table/DataTableComponent.tsx
  frontend/src/components/menu/Menu.tsx
  frontend/src/containers/Layout.tsx
  frontend/src/pages/apps-store/AllApplications.tsx
  frontend/src/pages/organization/OrganizationProfile.tsx
  frontend/src/pages/organization/Organizations.tsx
  frontend/src/pages/organization/table-headers/OrganizationsTable.headers.tsx
  frontend/src/pages/requests/components/RequestList.headers.tsx
  frontend/src/pages/requests/components/RequestList.tsx
  frontend/src/pages/users/Users.tsx
  frontend/src/pages/users/components/UserList/UserList.tsx
  frontend/src/pages/users/components/UserList/table-headers/UserListTable.headers.tsx
  frontend/src/pages/users/interfaces/User.interface.ts
  frontend/tailwind.config.js
Labels: back-end, front-end

#411 fix: [C4R-369] missing translations
  frontend/src/assets/locales/en/translation.json
  frontend/src/assets/locales/ro/translation.json
  frontend/src/pages/apps-store/components/EditApplication.tsx
  frontend/src/pages/apps-store/constants/ApplicationType.enum.ts
  frontend/src/pages/create-organziation/components/CreateOrganizationActivity.tsx
  frontend/src/pages/create-organziation/components/CreateOrganizationGeneral.tsx
  frontend/src/pages/create-organziation/components/CreateOrganizationLegal.tsx
  frontend/src/pages/create-organziation/components/CreateOrganizationUser.tsx
  frontend/src/pages/organization/Organization.tsx
  frontend/src/pages/organization/components/OrganizationActivity/OrganizationActivity.tsx
  frontend/src/pages/organization/components/OrganizationData/OrganizationData.tsx
  frontend/src/pages/organization/components/OrganizationData/components/ReportSummaryModal.tsx
  frontend/src/pages/organization/components/OrganizationFinancial/OrganizationFinancial.tsx
  frontend/src/pages/organization/components/OrganizationFinancial/components/ExpenseReportModal.tsx
  frontend/src/pages/organization/components/OrganizationFinancial/components/IncomeReportModal.tsx
  frontend/src/pages/organization/components/OrganizationGeneral/OrganizationGeneral.tsx
  frontend/src/pages/organization/components/OrganizationLegal/OrganizationLegal.tsx
  frontend/src/pages/organization/components/OrganizationLegal/components/DirectorModal.tsx
  frontend/src/pages/organization/components/OrganizationLegal/components/OtherModal.tsx
  frontend/src/pages/requests/components/Request.tsx
Labels: bug :bug:

#406 fix: [C4R-361] add delete confirmation modal for statute + set statute null on error
  frontend/src/assets/locales/en/translation.json
  frontend/src/assets/locales/ro/translation.json
  frontend/src/pages/create-organziation/components/CreateOrganizationLegal.tsx
  frontend/src/pages/organization/components/OrganizationLegal/OrganizationLegal.tsx
Labels: bug :bug:

#410 fix: [C4R-357] show "all" option for filters
  frontend/src/assets/locales/en/translation.json
  frontend/src/assets/locales/ro/translation.json
  frontend/src/pages/application/constants/filter.constants.ts
  frontend/src/pages/apps-store/constants/ApplicationStatus.constant.ts
  frontend/src/pages/organization/Organizations.tsx
  frontend/src/pages/organization/constants/filters.constants.ts
  frontend/src/pages/users/components/UserList/UserList.tsx
  frontend/src/pages/users/constants/filters.constants.ts
Labels: bug :bug:
